version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: skinft
    # volumes:
    #   - ./data:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/

  node:
    image: skinft/node
    build:
      context: .
      dockerfile: containers/node/Dockerfile
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./src:/home/node/src  # for development purposes
    ports:
      - 3000:3000
    working_dir: /home/node
    command: npm run dev
