version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: skinft
    volumes:
      - ./containers/mongo:/docker-entrypoint-initdb.d

  node:
    image: skinft/node
    build:
      context: .
      dockerfile: containers/node/Dockerfile
    depends_on:
      - mongo
    restart: always
    ports:
      - 3000:3000
    working_dir: /home/node
    command: npm start
